title: Tomasz Dygas - SAP Developer Portfolio
description: >-
  SAP Developer, Solution Architect & DevOps Specialist based in Warsaw, Poland.
  Over 15 years of experience in SAP development, architecture, and DevOps.
theme: just-the-docs

url: "https://lolek24.github.io"

aux_links:
  GitHub: https://github.com/lolek24
